export SNOWFLAKE_ACCOUNT="TA48442-VP79329"
export SNOWFLAKE_USER="PBOSKOVIC@ATTENTIVEMOBILE.COM"
export SNOWFLAKE_WAREHOUSE="ENGBI_SVC_XL_WH"
export SNOWFLAKE_DATABASE="ATTENTIVE"
export SNOWFLAKE_SCHEMA="CONCIERGE"
export SNOWFLAKE_AUTHENTICATOR="externalbrowser"

# optional
export SNOWFLAKE_ROLE="SNOWFLAKE-ANALYST"